# -*- org -*-
#+TITLE: Touching the unstable scale
#+AUTHOR: Isaac R. Wang
#+EMAIL: isaac.wang.us@gmail.com

* Introduction
This branch records some early trial on the unstable scale. The calculation results from the code in this branch are trials that fails to give results to be shown in the final paper. But the trial process are useful and should be recorded. To get the code that gives the results in the paper, please see the master branch.

* Bounce solution for the Euclidean action of tunneling rate
The effective potential at the zero temperature is calculated in both 2d dynamics, and in 1d dynamics with the light scalar integrated out.

We use =Mathematica= code [[file:Vacuum_stability_1d.nb][stability_1d]] for the bounce solution of the 1d dynamics. No proper bounce solution are found there.

We use =Mathematica= code [[file:Vacuum_stability_2d.nb][stability_2d]] to plot the 2d effective potential.

The 2d dynamics is also tried in [[file:Vacuum_stability.ipynb][jupyter notebook]] with =cosmoTransition= package.

* Running coupling
Running coupling are calculated to check the energy scale where the effective quartic coupling becomes negative. See [[file:instability.nb][code]] for detail.

This result is not shown in the final paper since we have a more detailed treatment for the vacuum stability problem.
